// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TashGresOpto.Data.Context;

#nullable disable

namespace TashGresOpto.Data.Migrations
{
    [DbContext(typeof(OptoDbContext))]
    [Migration("20260706062206_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("TashGresOpto.Data.Entities.Baxta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("DOP")
                        .HasColumnType("REAL");

                    b.Property<double>("GKBT")
                        .HasColumnType("REAL");

                    b.Property<int>("MMDD")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("NB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NZ")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Nagr")
                        .HasColumnType("REAL");

                    b.Property<double>("PUG")
                        .HasColumnType("REAL");

                    b.Property<double>("SN")
                        .HasColumnType("REAL");

                    b.Property<int>("Smena")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TOP")
                        .HasColumnType("REAL");

                    b.Property<double>("TPP")
                        .HasColumnType("REAL");

                    b.Property<double>("TPW")
                        .HasColumnType("REAL");

                    b.Property<double>("WAK")
                        .HasColumnType("REAL");

                    b.Property<double>("WSEGO")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("MMDD", "NB");

                    b.ToTable("Baxta");
                });

            modelBuilder.Entity("TashGresOpto.Data.Entities.BaxtaCounter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockNumber")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Coefficient")
                        .HasColumnType("REAL");

                    b.Property<string>("CounterNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CounterType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InstallDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ReadingEnd")
                        .HasColumnType("REAL");

                    b.Property<double>("ReadingStart")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("BaxtaCounter");
                });

            modelBuilder.Entity("TashGresOpto.Data.Entities.BaxtaParams", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("DRO")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("O2")
                        .HasColumnType("REAL");

                    b.Property<double>("POP")
                        .HasColumnType("REAL");

                    b.Property<int>("PWD")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Smena")
                        .HasColumnType("INTEGER");

                    b.Property<double>("THW")
                        .HasColumnType("REAL");

                    b.Property<double>("TIM")
                        .HasColumnType("REAL");

                    b.Property<double>("TK")
                        .HasColumnType("REAL");

                    b.Property<double>("TOP")
                        .HasColumnType("REAL");

                    b.Property<double>("TPP")
                        .HasColumnType("REAL");

                    b.Property<double>("TPW")
                        .HasColumnType("REAL");

                    b.Property<double>("TUG")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("BaxtaParams");
                });

            modelBuilder.Entity("TashGresOpto.Data.Entities.PereType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<double>("Coefficient")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PereType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "RVV",
                            Coefficient = 10.6,
                            IsActive = true,
                            Name = "ЋвЄ«озҐ­ЁҐ 1 ђ‚‚",
                            Note = "",
                            Unit = "ЄЈ г.в./Њ‚въз"
                        },
                        new
                        {
                            Id = 2,
                            Code = "CN",
                            Coefficient = 7.0999999999999996,
                            IsActive = true,
                            Name = "ђ Ў®в  1 –Ќ",
                            Note = "",
                            Unit = "ЄЈ г.в./Њ‚въз"
                        },
                        new
                        {
                            Id = 3,
                            Code = "PVD",
                            Coefficient = 6.0,
                            IsActive = true,
                            Name = "ЋвЄ«озҐ­ЁҐ ЈагЇЇл Џ‚„",
                            Note = "",
                            Unit = "ЄЈ г.в./Њ‚въз"
                        },
                        new
                        {
                            Id = 4,
                            Code = "SPD",
                            Coefficient = 1.8999999999999999,
                            IsActive = true,
                            Name = "ђ Ў®в  ЎҐ§ ®Ў®Ёе ‘Џ„",
                            Note = "",
                            Unit = "ЄЈ г.в./Њ‚въз"
                        },
                        new
                        {
                            Id = 5,
                            Code = "OE",
                            Coefficient = 0.69999999999999996,
                            IsActive = true,
                            Name = "‚Є«озҐ­ЁҐ ўв®а®Ј® Ћќ",
                            Note = "",
                            Unit = "ЄЈ г.в./Њ‚въз"
                        },
                        new
                        {
                            Id = 6,
                            Code = "ROU",
                            Coefficient = 20.0,
                            IsActive = true,
                            Name = "ЏҐаҐў®¤ бҐв.Ї®¤®Ја. ­  ђЋ“",
                            Note = "",
                            Unit = "ЄЈ г.в."
                        },
                        new
                        {
                            Id = 7,
                            Code = "AVAR",
                            Coefficient = 444.0,
                            IsActive = true,
                            Name = "ђ Ў®в   ў а. ўЇа.",
                            Note = "",
                            Unit = "бЇҐжЁ «м­ п"
                        });
                });

            modelBuilder.Entity("TashGresOpto.Data.Entities.Perejeg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("FuelConsumption")
                        .HasColumnType("REAL");

                    b.Property<double>("Hours")
                        .HasColumnType("REAL");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL");

                    b.Property<double>("SpecificOverburn")
                        .HasColumnType("REAL");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.HasIndex("Date", "BlockNumber");

                    b.ToTable("Perejeg");
                });

            modelBuilder.Entity("TashGresOpto.Data.Entities.Selektor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockNumber")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Consumption")
                        .HasColumnType("REAL");

                    b.Property<string>("CounterNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("MechanismName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("MechanismNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("ReadingEnd")
                        .HasColumnType("REAL");

                    b.Property<double>("ReadingStart")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Date", "MechanismNumber");

                    b.ToTable("Selektor");
                });

            modelBuilder.Entity("TashGresOpto.Data.Entities.Wyrab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("Generation")
                        .HasColumnType("REAL");

                    b.Property<double>("GeneratorCoefficient")
                        .HasColumnType("REAL");

                    b.Property<string>("GeneratorCounterNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("Hours")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("Power")
                        .HasColumnType("REAL");

                    b.Property<double>("ReadingEnd")
                        .HasColumnType("REAL");

                    b.Property<double>("ReadingStart")
                        .HasColumnType("REAL");

                    b.Property<double>("SN")
                        .HasColumnType("REAL");

                    b.Property<double>("SNCoefficient")
                        .HasColumnType("REAL");

                    b.Property<string>("SNCounterNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("SNPercent")
                        .HasColumnType("REAL");

                    b.Property<double>("SNReadingEnd")
                        .HasColumnType("REAL");

                    b.Property<double>("SNReadingStart")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Date", "BlockNumber");

                    b.ToTable("Wyrab");
                });

            modelBuilder.Entity("TashGresOpto.Data.Entities.WyrabCounter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Coefficient")
                        .HasColumnType("REAL");

                    b.Property<string>("CounterNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MechanismName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("MechanismNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MechanismType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("ReadingEnd")
                        .HasColumnType("REAL");

                    b.Property<double>("ReadingStart")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("WyrabCounter");
                });

            modelBuilder.Entity("TashGresOpto.Data.Entities.Perejeg", b =>
                {
                    b.HasOne("TashGresOpto.Data.Entities.PereType", "PereType")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PereType");
                });
#pragma warning restore 612, 618
        }
    }
}
