// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TashGresOpto.Data.Context;

#nullable disable

namespace TashGresOpto.Data.Migrations
{
    [DbContext(typeof(OptoDbContext))]
    partial class OptoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("TashGresOpto.Data.Entities.Baxta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("DOP")
                        .HasColumnType("REAL");

                    b.Property<double>("GKBT")
                        .HasColumnType("REAL");

                    b.Property<int>("MMDD")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("NB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NZ")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Nagr")
                        .HasColumnType("REAL");

                    b.Property<double>("PUG")
                        .HasColumnType("REAL");

                    b.Property<double>("SN")
                        .HasColumnType("REAL");

                    b.Property<int>("Smena")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TOP")
                        .HasColumnType("REAL");

                    b.Property<double>("TPP")
                        .HasColumnType("REAL");

                    b.Property<double>("TPW")
                        .HasColumnType("REAL");

                    b.Property<double>("WAK")
                        .HasColumnType("REAL");

                    b.Property<double>("WSEGO")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("MMDD", "NB");

                    b.ToTable("Baxta");
                });

            modelBuilder.Entity("TashGresOpto.Data.Entities.BaxtaCounter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockNumber")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Coefficient")
                        .HasColumnType("REAL");

                    b.Property<string>("CounterNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CounterType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InstallDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ReadingEnd")
                        .HasColumnType("REAL");

                    b.Property<double>("ReadingStart")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("BaxtaCounter");
                });

            modelBuilder.Entity("TashGresOpto.Data.Entities.BaxtaParams", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("DRO")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("O2")
                        .HasColumnType("REAL");

                    b.Property<double>("POP")
                        .HasColumnType("REAL");

                    b.Property<int>("PWD")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Smena")
                        .HasColumnType("INTEGER");

                    b.Property<double>("THW")
                        .HasColumnType("REAL");

                    b.Property<double>("TIM")
                        .HasColumnType("REAL");

                    b.Property<double>("TK")
                        .HasColumnType("REAL");

                    b.Property<double>("TOP")
                        .HasColumnType("REAL");

                    b.Property<double>("TPP")
                        .HasColumnType("REAL");

                    b.Property<double>("TPW")
                        .HasColumnType("REAL");

                    b.Property<double>("TUG")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("BaxtaParams");
                });

            modelBuilder.Entity("TashGresOpto.Data.Entities.Perejeg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Blok1")
                        .HasColumnType("REAL");

                    b.Property<double>("Blok10")
                        .HasColumnType("REAL");

                    b.Property<double>("Blok11")
                        .HasColumnType("REAL");

                    b.Property<double>("Blok12")
                        .HasColumnType("REAL");

                    b.Property<double>("Blok2")
                        .HasColumnType("REAL");

                    b.Property<double>("Blok3")
                        .HasColumnType("REAL");

                    b.Property<double>("Blok4")
                        .HasColumnType("REAL");

                    b.Property<double>("Blok5")
                        .HasColumnType("REAL");

                    b.Property<double>("Blok6")
                        .HasColumnType("REAL");

                    b.Property<double>("Blok7")
                        .HasColumnType("REAL");

                    b.Property<double>("Blok8")
                        .HasColumnType("REAL");

                    b.Property<double>("Blok9")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Nome")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nomer")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Sblok")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Nome", "Nomer");

                    b.ToTable("Perejeg");
                });

            modelBuilder.Entity("TashGresOpto.Data.Entities.PerejegType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Nomer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PerejegTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 7, 10, 9, 48, 6, 795, DateTimeKind.Local).AddTicks(4326),
                            Name = "Отключение РВВ",
                            Nomer = 1,
                            Note = ""
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 7, 10, 9, 48, 6, 795, DateTimeKind.Local).AddTicks(4339),
                            Name = "Снижение СН",
                            Nomer = 2,
                            Note = ""
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 7, 10, 9, 48, 6, 795, DateTimeKind.Local).AddTicks(4341),
                            Name = "Отключение группы ПВД",
                            Nomer = 3,
                            Note = ""
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 7, 10, 9, 48, 6, 795, DateTimeKind.Local).AddTicks(4342),
                            Name = "Снижение нагр. парообр.",
                            Nomer = 4,
                            Note = ""
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 7, 10, 9, 48, 6, 795, DateTimeKind.Local).AddTicks(4343),
                            Name = "Отключение острого ОЕ",
                            Nomer = 5,
                            Note = ""
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2026, 7, 10, 9, 48, 6, 795, DateTimeKind.Local).AddTicks(4344),
                            Name = "Перевод дн.мельниц на уголь",
                            Nomer = 6,
                            Note = ""
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2026, 7, 10, 9, 48, 6, 795, DateTimeKind.Local).AddTicks(4346),
                            Name = "Снижение авар. рез.",
                            Nomer = 7,
                            Note = ""
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2026, 7, 10, 9, 48, 6, 795, DateTimeKind.Local).AddTicks(4347),
                            Name = "Сумма 1-7",
                            Nomer = 8,
                            Note = ""
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2026, 7, 10, 9, 48, 6, 795, DateTimeKind.Local).AddTicks(4348),
                            Name = "Отключение РВВ",
                            Nomer = 9,
                            Note = ""
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2026, 7, 10, 9, 48, 6, 795, DateTimeKind.Local).AddTicks(4349),
                            Name = "Снижение СН",
                            Nomer = 10,
                            Note = ""
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2026, 7, 10, 9, 48, 6, 795, DateTimeKind.Local).AddTicks(4350),
                            Name = "Отключение группы ПВД",
                            Nomer = 11,
                            Note = ""
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2026, 7, 10, 9, 48, 6, 795, DateTimeKind.Local).AddTicks(4351),
                            Name = "Снижение нагр. парообр.",
                            Nomer = 12,
                            Note = ""
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2026, 7, 10, 9, 48, 6, 795, DateTimeKind.Local).AddTicks(4352),
                            Name = "Отключение острого ОЕ",
                            Nomer = 13,
                            Note = ""
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2026, 7, 10, 9, 48, 6, 795, DateTimeKind.Local).AddTicks(4353),
                            Name = "Перевод дн.мельниц на уголь",
                            Nomer = 14,
                            Note = ""
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2026, 7, 10, 9, 48, 6, 795, DateTimeKind.Local).AddTicks(4354),
                            Name = "Снижение авар. рез.",
                            Nomer = 15,
                            Note = ""
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2026, 7, 10, 9, 48, 6, 795, DateTimeKind.Local).AddTicks(4355),
                            Name = "Сумма 9-15",
                            Nomer = 16,
                            Note = ""
                        });
                });

            modelBuilder.Entity("TashGresOpto.Data.Entities.Selektor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockNumber")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Consumption")
                        .HasColumnType("REAL");

                    b.Property<string>("CounterNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("MechanismName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("MechanismNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("ReadingEnd")
                        .HasColumnType("REAL");

                    b.Property<double>("ReadingStart")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Date", "MechanismNumber");

                    b.ToTable("Selektor");
                });

            modelBuilder.Entity("TashGresOpto.Data.Entities.Wyrab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("Generation")
                        .HasColumnType("REAL");

                    b.Property<double>("GeneratorCoefficient")
                        .HasColumnType("REAL");

                    b.Property<string>("GeneratorCounterNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("Hours")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("Power")
                        .HasColumnType("REAL");

                    b.Property<double>("ReadingEnd")
                        .HasColumnType("REAL");

                    b.Property<double>("ReadingStart")
                        .HasColumnType("REAL");

                    b.Property<double>("SN")
                        .HasColumnType("REAL");

                    b.Property<double>("SNCoefficient")
                        .HasColumnType("REAL");

                    b.Property<string>("SNCounterNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("SNPercent")
                        .HasColumnType("REAL");

                    b.Property<double>("SNReadingEnd")
                        .HasColumnType("REAL");

                    b.Property<double>("SNReadingStart")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Date", "BlockNumber");

                    b.ToTable("Wyrab");
                });

            modelBuilder.Entity("TashGresOpto.Data.Entities.WyrabCounter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Coefficient")
                        .HasColumnType("REAL");

                    b.Property<string>("CounterNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MechanismName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("MechanismNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MechanismType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("ReadingEnd")
                        .HasColumnType("REAL");

                    b.Property<double>("ReadingStart")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("WyrabCounter");
                });

            modelBuilder.Entity("TashGresOpto.Data.Entities.WyrabReplacement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CounterNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("EnergyBypass")
                        .HasColumnType("REAL");

                    b.Property<double>("InitialReading")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<double>("NewCoefficient")
                        .HasColumnType("REAL");

                    b.Property<string>("NewCounterSerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("OldFinalReading")
                        .HasColumnType("REAL");

                    b.Property<double>("ReplacedFinalReading")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("ReplacementDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReplacementDate", "CounterNumber");

                    b.ToTable("WyrabReplacement");
                });

            modelBuilder.Entity("TashGresOpto.Data.Entities.WyrabReplacementHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CounterNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("EnergyBypass")
                        .HasColumnType("REAL");

                    b.Property<double>("FinalReading")
                        .HasColumnType("REAL");

                    b.Property<double>("OldBypassReading")
                        .HasColumnType("REAL");

                    b.Property<double>("OldCoefficient")
                        .HasColumnType("REAL");

                    b.Property<string>("OldSerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReplacementDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReplacementDate", "CounterNumber");

                    b.ToTable("WyrabReplacementHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
